/**
 * scaffold-ui — turn a Claude Design export into a maintainable `packages/ui`
 * (DTCG tokens → Style Dictionary → Tailwind v4 `@theme`) + a component skeleton.
 *
 *   pnpm run scaffold:ui -- --src <exportDir> --out <packagesDir> [--name ui] [--ds-name "My DS"]
 *
 * `--src` is a directory of exported Claude Design files (the `project/` folder from a
 * handoff bundle, or a plain `export` dir). The generator:
 *   1. Parses design tokens from the export's token CSS (primitive + semantic layers).
 *   2. Emits DTCG JSON (the durable source of truth) under packages/tokens/src/.
 *   3. Writes a Style Dictionary config that compiles to Tailwind v4 `@theme` + tokens.ts,
 *      and runs it once for an initial build.
 *   4. Scaffolds packages/ui (styles, primitives/, components/, index.ts, CLAUDE.md).
 *   5. Copies the raw export to packages/ui/_design-source/ + fonts, and writes PROMPT.md.
 *
 * Components are NOT auto-converted (the prototype JSX is Babel-in-browser). They are
 * scaffolded + the prototype is preserved as reference so Claude Code can port them
 * against the clean semantic tokens.
 */
import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import StyleDictionary from "style-dictionary";

// ---------- Style Dictionary formats (shared by the one-time build AND the
// style-dictionary.config.mjs we write for the user — serialized via .toString()
// so there's a single source of truth). Self-contained: no outer references.

/* eslint-disable */
const tailwindThemeFormat = ({ dictionary }: any): string => {
  const NS: Record<string, string> = { color: "color", spacing: "spacing", radius: "radius", font: "font", "font-weight": "font-weight", shadow: "shadow", text: "text" };
  const root: string[] = [], theme: string[] = [];
  for (const t of dictionary.allTokens) {
    const layer = t.$extensions?.["cd.layer"] ?? (String(t.original?.$value ?? "").startsWith("{") ? "semantic" : "primitive");
    const name = "--" + t.path.join("-");
    const orig = t.original?.$value ?? t.$value;
    const isAlias = typeof orig === "string" && /^\{[^}]+\}$/.test(orig);
    const val = isAlias ? "var(--" + orig.slice(1, -1).split(".").join("-") + ")" : (t.$value ?? t.value);
    if (layer === "primitive") root.push("  " + name + ": " + val + ";");
    else if (NS[t.path[0]]) theme.push("  " + name + ": " + val + ";");
    else root.push("  " + name + ": " + val + ";");
  }
  return ":root {\n" + root.join("\n") + "\n}\n\n@theme inline {\n" + theme.join("\n") + "\n}\n";
};

const tokensTsFormat = ({ dictionary }: any): string => {
  const NS = ["color", "spacing", "radius", "font", "font-weight", "shadow", "text"];
  const semantic = dictionary.allTokens.filter((t: any) => (t.$extensions?.["cd.layer"] ?? "") === "semantic" && NS.includes(t.path[0]));
  const lines = semantic.map((t: any) => '  "' + t.path.join(".") + '": "var(--' + t.path.join("-") + ')",');
  return "// Generated by scaffold-ui. Semantic design tokens as CSS var references.\nexport const tokens = {\n" + lines.join("\n") + "\n} as const;\nexport type TokenName = keyof typeof tokens;\n";
};
/* eslint-enable */

// ---------- args ----------
// Filled in by run(); shared by `pnpm run scaffold:ui` and `claude-design scaffold`.
let ARGV: string[] = [];
let SRC: string | undefined;
let OUT: string | undefined;
let PKG = "ui";
let DS_NAME = "Design System";

function arg(flag: string, def?: string): string | undefined {
  const i = ARGV.indexOf(flag);
  return i >= 0 && ARGV[i + 1] ? ARGV[i + 1] : def;
}

export async function run(argv: string[]): Promise<void> {
  ARGV = argv;
  SRC = arg("--src");
  OUT = arg("--out");
  PKG = arg("--name", "ui")!;
  DS_NAME = arg("--ds-name", "Design System")!;
  if (!SRC || !OUT) {
    console.error("usage: scaffold --src <exportDir> --out <packagesDir> [--name ui] [--ds-name \"My DS\"]");
    process.exit(1);
  }
  await main();
}

// ---------- token parsing ----------
interface Decl { name: string; value: string; }
type Group = "color" | "spacing" | "radius" | "font" | "font-weight" | "shadow" | "text" | "other";

interface Token {
  cssName: string;      // original, e.g. p-neutral-500 / background
  group: Group;
  key: string;          // cleaned key within group, e.g. neutral-500 / background
  type: string;         // DTCG $type
  layer: "primitive" | "semantic";
  rawValue: string;     // literal or var(--x)
  refName?: string;     // if alias: referenced cssName
}

const COLOR_RE = /(oklch|oklab|hsla?|rgba?|color|lab|lch)\s*\(|#[0-9a-fA-F]{3,8}\b|\b(white|black|transparent|currentColor)\b/;
const DIM_RE = /^-?\d*\.?\d+(px|rem|em|%|vh|vw|dvh|svh)$/;
const NUM_RE = /^-?\d*\.?\d+$/;

function readDeclsFromCss(css: string): Decl[] {
  const out: Decl[] = [];
  const re = /(--[\w-]+)\s*:\s*([^;]+);/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css))) out.push({ name: m[1].slice(2), value: m[2].trim() });
  return out;
}

function resolveLiteral(value: string, map: Map<string, string>, seen = new Set<string>()): string {
  const m = value.match(/^var\(\s*--([\w-]+)\s*(?:,[^)]*)?\)$/);
  if (!m) return value;
  const ref = m[1];
  if (seen.has(ref)) return value;
  seen.add(ref);
  const next = map.get(ref);
  return next ? resolveLiteral(next, map, seen) : value;
}

function groupAndType(cssName: string, literal: string): { group: Group; type: string } {
  const n = cssName.toLowerCase();
  if (COLOR_RE.test(literal)) return { group: "color", type: "color" };
  if (/\bweight\b/.test(n)) return { group: "font-weight", type: "fontWeight" };
  if (/font|family|typeface/.test(n) && /[",]/.test(literal)) return { group: "font", type: "fontFamily" };
  if (/shadow|elevation/.test(n)) return { group: "shadow", type: "shadow" };
  if (/radius|radii|rounded/.test(n)) return { group: "radius", type: "dimension" };
  if (DIM_RE.test(literal)) {
    if (/font-size|text-|leading|tracking|--fs-|size-text/.test(n)) return { group: "text", type: "dimension" };
    if (/space|spacing|gap|inset|margin|padding|size|width|height/.test(n)) return { group: "spacing", type: "dimension" };
    return { group: "spacing", type: "dimension" };
  }
  if (NUM_RE.test(literal)) return { group: "other", type: "number" };
  return { group: "other", type: "other" };
}

function cleanKey(cssName: string, group: Group): string {
  let k = cssName.replace(/^p-/, ""); // drop primitive prefix
  // avoid duplicating the group word at the start (e.g. radius-md -> md under radius)
  k = k.replace(new RegExp(`^${group}-`), "");
  return k || cssName.replace(/^p-/, "");
}

// ---------- main ----------
/** Find the token CSS files to parse, handling design-system and project layouts. */
async function resolveTokenFiles(srcDir: string): Promise<string[]> {
  // 1) canonical layered design-system source
  if (existsSync(path.join(srcDir, "system/tokens.css"))) {
    return ["system/tokens.css", "miniapp.css"].map((r) => path.join(srcDir, r)).filter(existsSync);
  }
  // 2) design project handoff: bound design system under _ds/<ds>/
  const dsRoot = path.join(srcDir, "_ds");
  if (existsSync(dsRoot)) {
    const dirs = (await fs.readdir(dsRoot, { withFileTypes: true })).filter((e) => e.isDirectory());
    const files: string[] = [];
    for (const d of dirs) {
      const dsDir = path.join(dsRoot, d.name);
      const tokensDir = path.join(dsDir, "tokens");
      if (existsSync(tokensDir)) {
        for (const f of await fs.readdir(tokensDir)) if (f.endsWith(".css")) files.push(path.join(tokensDir, f));
      }
      for (const single of ["tokens.css", "colors_and_type.css", "styles.css"]) {
        if (files.length === 0 && existsSync(path.join(dsDir, single))) files.push(path.join(dsDir, single));
      }
    }
    if (files.length) return files;
  }
  // 3) flattened single-file sources at the root
  return ["tokens.css", "colors_and_type.css", "styles.css", "theme.css"]
    .map((r) => path.join(srcDir, r))
    .filter(existsSync);
}

async function main(): Promise<void> {
  const srcDir = path.resolve(SRC!);
  const outDir = path.resolve(OUT!);
  const tokensPkg = path.join(outDir, "tokens");
  const uiPkg = path.join(outDir, PKG);

  // 1) collect token CSS. Layouts vary:
  //  - design SYSTEM export: canonical system/tokens.css (+ additive miniapp.css), or
  //    flattened colors_and_type.css at the root.
  //  - design PROJECT handoff: tokens live in the bound DS under
  //    `_ds/<ds>/tokens/*.css` (+ that DS's styles.css).
  // Prefer the layered source; avoid mixing flattened literals with var() layering.
  const tokenFiles = await resolveTokenFiles(srcDir);
  if (tokenFiles.length === 0) {
    console.error(`No token CSS found under ${srcDir} (looked for system/tokens.css, _ds/*/tokens/*.css, tokens.css, colors_and_type.css, styles.css).`);
    process.exit(1);
  }
  const cssTexts: string[] = [];
  let fontImport = "";
  for (const p of tokenFiles) {
    const t = await fs.readFile(p, "utf8");
    cssTexts.push(t);
    const fi = t.match(/@import url\(["']https:\/\/fonts\.googleapis[^)]+["']\)/);
    if (fi && !fontImport) fontImport = fi[0] + ";";
  }

  // 2) parse + dedupe decls (last wins), build literal map
  const declMap = new Map<string, string>();
  for (const css of cssTexts) for (const d of readDeclsFromCss(css)) declMap.set(d.name, d.value);

  const tokens: Token[] = [];
  const cssNameToPath = new Map<string, { group: Group; key: string }>();
  for (const [cssName, rawValue] of declMap) {
    const literal = resolveLiteral(rawValue, declMap);
    const { group, type } = groupAndType(cssName, literal);
    // Classify: aliases are semantic; otherwise raw ramps / p-* / named colors are
    // primitives, and any other *named* literal (border, glass, on-media…) is a
    // literal-valued semantic token (so it still becomes a Tailwind utility).
    const isAlias = /^var\(/.test(rawValue);
    const isRamp = /^p-/.test(cssName) || /-\d{2,3}$/.test(cssName) || /^(white|black|transparent|current[A-Za-z]*)$/.test(cssName);
    const layer: Token["layer"] = isAlias ? "semantic" : isRamp ? "primitive" : "semantic";
    const key = cleanKey(cssName, group);
    const refMatch = rawValue.match(/^var\(\s*--([\w-]+)/);
    tokens.push({ cssName, group, key, type, layer, rawValue, refName: refMatch?.[1] });
    cssNameToPath.set(cssName, { group, key });
  }

  // 3) write DTCG JSON (primitive/<group>.tokens.json, semantic/<group>.tokens.json)
  const byLayerGroup = new Map<string, Record<string, unknown>>(); // `${layer}/${group}` -> nested obj
  for (const t of tokens) {
    const fileKey = `${t.layer}/${t.group}`;
    const obj = byLayerGroup.get(fileKey) ?? {};
    const groupObj = (obj[t.group] as Record<string, unknown>) ?? {};
    let value: string;
    if (t.layer === "semantic" && t.refName && cssNameToPath.has(t.refName)) {
      const ref = cssNameToPath.get(t.refName)!;
      value = `{${ref.group}.${ref.key}}`;
    } else {
      value = resolveLiteral(t.rawValue, declMap);
    }
    groupObj[t.key] = { $value: value, $type: t.type, $extensions: { "cd.layer": t.layer } };
    obj[t.group] = groupObj;
    byLayerGroup.set(fileKey, obj);
  }
  for (const [fileKey, obj] of byLayerGroup) {
    const out = path.join(tokensPkg, "src", `${fileKey}.tokens.json`);
    await fs.mkdir(path.dirname(out), { recursive: true });
    await fs.writeFile(out, JSON.stringify(obj, null, 2) + "\n");
  }

  const counts = tokens.reduce((m, t) => ((m[t.layer] = (m[t.layer] ?? 0) + 1), m), {} as Record<string, number>);

  // 4) Write the SD config (for the user's future rebuilds) + run a one-time build
  // now using THIS repo's style-dictionary (the output dir has no node_modules yet).
  await fs.writeFile(path.join(tokensPkg, "style-dictionary.config.mjs"), sdConfig());
  await fs.writeFile(path.join(tokensPkg, "package.json"), tokensPackageJson());
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: [path.join(tokensPkg, "src/**/*.tokens.json")],
    hooks: { formats: { "tailwind/theme": tailwindThemeFormat, "ts/tokens": tokensTsFormat } },
    platforms: {
      css: { transforms: [], buildPath: path.join(tokensPkg, "build") + "/", files: [{ destination: "theme.css", format: "tailwind/theme" }] },
      ts: { transforms: [], buildPath: path.join(tokensPkg, "build") + "/", files: [{ destination: "tokens.ts", format: "ts/tokens" }] },
    },
  });
  await sd.buildAllPlatforms();

  // 5) scaffold packages/ui
  await fs.mkdir(path.join(uiPkg, "src", "styles"), { recursive: true });
  await fs.mkdir(path.join(uiPkg, "src", "primitives"), { recursive: true });
  await fs.mkdir(path.join(uiPkg, "src", "components"), { recursive: true });
  await fs.writeFile(path.join(uiPkg, "src", "primitives", ".gitkeep"), "");
  await fs.writeFile(path.join(uiPkg, "src", "components", ".gitkeep"), "");
  await fs.writeFile(path.join(uiPkg, "src", "styles", "styles.css"), stylesCss(fontImport));
  await fs.writeFile(path.join(uiPkg, "src", "index.ts"), indexTs());
  await fs.writeFile(path.join(uiPkg, "package.json"), uiPackageJson());
  await fs.writeFile(path.join(uiPkg, "CLAUDE.md"), uiClaudeMd());

  // 6) copy raw export as reference + fonts; write PROMPT.md
  await copyDir(srcDir, path.join(uiPkg, "_design-source"));
  await fs.writeFile(path.join(outDir, "PROMPT.md"), promptMd(counts));

  console.log(`✅ scaffolded:`);
  console.log(`   ${path.relative(process.cwd(), tokensPkg)}  (${counts.primitive ?? 0} primitive + ${counts.semantic ?? 0} semantic tokens → DTCG + theme.css + tokens.ts)`);
  console.log(`   ${path.relative(process.cwd(), uiPkg)}  (styles/, primitives/, components/, _design-source/)`);
  console.log(`   ${path.relative(process.cwd(), path.join(outDir, "PROMPT.md"))}  (component-porting instructions for Claude Code)`);
}

async function copyDir(src: string, dst: string): Promise<void> {
  await fs.mkdir(dst, { recursive: true });
  for (const e of await fs.readdir(src, { withFileTypes: true })) {
    const s = path.join(src, e.name), d = path.join(dst, e.name);
    if (e.isDirectory()) await copyDir(s, d);
    else await fs.copyFile(s, d);
  }
}

// ---------- generated file templates ----------
function sdConfig(): string {
  // Serialize the SAME format functions used for the one-time build so the user's
  // rebuilds produce identical output (single source of truth).
  return `import StyleDictionary from "style-dictionary";

const tailwindThemeFormat = ${tailwindThemeFormat.toString()};

const tokensTsFormat = ${tokensTsFormat.toString()};

export default {
  usesDtcg: true,
  source: ["src/**/*.tokens.json"],
  hooks: { formats: { "tailwind/theme": tailwindThemeFormat, "ts/tokens": tokensTsFormat } },
  platforms: {
    css: { transforms: [], buildPath: "build/", files: [{ destination: "theme.css", format: "tailwind/theme" }] },
    ts: { transforms: [], buildPath: "build/", files: [{ destination: "tokens.ts", format: "ts/tokens" }] },
  },
};
`;
}

function tokensPackageJson(): string {
  return JSON.stringify({
    name: "@design/tokens",
    version: "0.0.0",
    private: true,
    type: "module",
    exports: { "./theme.css": "./build/theme.css", "./tokens": "./build/tokens.ts" },
    scripts: { build: "style-dictionary build --config style-dictionary.config.mjs" },
    devDependencies: { "style-dictionary": "^4.0.0" },
  }, null, 2) + "\n";
}

function stylesCss(fontImport: string): string {
  return `/* ${PKG} entry stylesheet. Tailwind v4 + generated design tokens. */
${fontImport ? fontImport + "\n" : ""}@import "tailwindcss";
@import "@design/tokens/theme.css";

/* If consuming this package from an app, ensure the app's Tailwind entry scans it:
   @source "../../packages/${PKG}/src"; */
`;
}

function indexTs(): string {
  return `// Public surface of the ${PKG} package. Re-export primitives + components here
// as you port them. Keep this barrel as the single discoverable manifest.
export {};
`;
}

function uiPackageJson(): string {
  return JSON.stringify({
    name: `@design/${PKG}`,
    version: "0.0.0",
    private: true,
    type: "module",
    main: "src/index.ts",
    dependencies: { "@design/tokens": "workspace:*" },
  }, null, 2) + "\n";
}

function uiClaudeMd(): string {
  return `# ${PKG} — module context for coding agents

This package is a design-system UI library generated from a Claude Design export.

## Layout
- \`src/styles/styles.css\` — Tailwind v4 entry; imports \`@design/tokens/theme.css\`.
- \`src/primitives/\` — low-level building blocks (Button, Input, Box…). One folder each.
- \`src/components/\` — composites built from primitives. One folder each.
- \`src/index.ts\` — the public barrel; re-export everything consumable here.
- \`_design-source/\` — the original Claude Design export (REFERENCE ONLY, do not ship).

## Rules
- Consume **semantic tokens only** — Tailwind utilities like \`bg-background\`, \`text-foreground\`,
  \`text-primary\`, \`border-border\`, or \`var(--color-*)\`. Never hardcode hex; never use a
  primitive (\`--color-neutral-*\`) directly in a component.
- Tokens are **generated** (\`@design/tokens\`). Don't hand-edit \`theme.css\`; edit the DTCG
  JSON in \`packages/tokens/src/\` and rebuild (\`pnpm --filter @design/tokens build\`).
- One component per folder; kebab/PascalCase by identity. Never hand-version files (no \`-v2\`).

## Porting from \`_design-source/\`
The export's components are prototype JSX (Babel-in-browser). Recreate them as real
components in \`src/components/\`, reading the prototype + the chat transcripts for intent,
and wiring only semantic tokens. Don't copy the prototype structure verbatim.
`;
}

function promptMd(counts: Record<string, number>): string {
  return `# Build a UI package from this Claude Design export

Generated a \`packages/tokens\` (DTCG → Style Dictionary → Tailwind v4 \`@theme\`,
${counts.primitive ?? 0} primitive + ${counts.semantic ?? 0} semantic tokens) and a
\`packages/${PKG}\` skeleton for **${DS_NAME}**.

## What's done
- \`packages/tokens/src/**\` — DTCG token JSON (source of truth, primitive + semantic layers).
- \`packages/tokens/build/theme.css\` — Tailwind v4 \`@theme\` (semantics → utilities; primitives
  stay in \`:root\`; var() references preserved so runtime re-theming cascades).
- \`packages/tokens/build/tokens.ts\` — typed semantic token map.
- \`packages/${PKG}/\` — styles entry, \`primitives/\` + \`components/\` skeleton, \`index.ts\`, \`CLAUDE.md\`.
- \`packages/${PKG}/_design-source/\` — the raw export, kept as reference.

## Your job (port the components)
1. Read \`packages/${PKG}/_design-source/\` (and any \`chats/\` transcripts) for intent.
2. For each prototype component/screen, create a real component under
   \`packages/${PKG}/src/components/<Name>/\`, recreating it in the target stack
   (React/TS/Tailwind), consuming **semantic tokens only**.
3. Re-export from \`src/index.ts\`.
4. To change tokens, edit \`packages/tokens/src/**\` and rebuild — never hand-edit \`theme.css\`.

Rebuild tokens any time: \`pnpm --filter @design/tokens build\`.
`;
}
